[build]
  command = "npm run build"
  publish="dist"

[[headers]]
  for = "/*"
[headers.values]
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-Xss-Protection = "1; mode=block"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Content-Security-Policy = '''
        default-src 'none' ;
        object-src 'none' ;
        frame-ancestors 'none' ;
        frame-src https: ;
        connect-src 'self' https: ;
        script-src 'self' https: 'unsafe-inline' ;
        style-src 'self' https: 'unsafe-inline' ;
        font-src 'self' https: ;
        img-src 'self' https: blob: data: ;
        media-src 'self';
        form-action 'self' ;
        base-uri 'self' ;
        manifest-src 'self' ;
        worker-src 'self' ;
        upgrade-insecure-requests ;
      '''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
